

pool:
  vmImage: ubuntu-latest

variables:
  acrserviceconnection: 'cred-acr-serviceconnection'
  frontendrepository: 'credpay/frontend'
  userrepository: 'credpay/user-service'
  paymentrepository: 'credpay/payment-service'
  tag: '$(Build.BuildId)'

stages:
  - stage: terraform
    displayName: terraform infra
    jobs:
      - job: terraformapply
        displayName: terraform init and apply
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'terraform'
              backendServiceArm: 'Manual connection'
              backendAzureRmResourceGroupName: 'credpayrg'
              backendAzureRmStorageAccountName: 'credpaystate'
              backendAzureRmContainerName: 'statefile'
              backendAzureRmKey: 'credpay.terraform.tfstate'

# - task: TerraformTask@5
#   displayName: 'Force unlock Terraform state'
#   inputs:
#     provider: 'azurerm'
#     command: 'custom'
#     workingDirectory: 'terraform'
#     commandOptions: 'force-unlock -force b40e4f7c-3ada-7885-673a-b8c7f52c8042'
#     environmentServiceNameAzureRM: 'Manual connection'


          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: 'terraform'
              environmentServiceNameAzureRM: 'Manual connection'












# stages:
#   - stage: dockerbuild
#     displayName: dockerbuild
#     jobs:
#       - job: buildPushImages
#         steps:
#           - checkout: self
#           - task: Docker@2
#             inputs:
#               containerRegistry: 'cred-acr-serviceconnection'
#               repository: '$(frontendrepository)'
#               command: 'buildAndPush'
#               Dockerfile: 'frontend-react/Dockerfile'
#               buildContext: 'frontend-react'
#               tags: |
#                 $(tag)
#                 latest